### ISSUE TITLE
RubyGem Request

### ISSUE THREAD

**Issue by coolacid** [steakknife/oui#1]
Please to include this on RubyGem?

**Comment by steakknife** [comment]
There's already a ruby gem named oui. :(

If using bundler,

```ruby
gem 'oui', github: 'steakknife/oui'
```

**Comment by coolacid** [comment]
Yeah Saw that - would still be nice to have an alternative name. 

To produce a logstash plugin, pulling gems via other methods other then rubygems.org is pretty painful. :(

**Comment by steakknife** [comment]
Before publishing, #2 needs to be fixed.

**Comment by coolacid** [comment]
Toats Fair ;)

**Comment by steakknife** [comment]
```shell
gem cert --add <(curl -L https://gist.github.com/steakknife/5333881/raw/gem-public_cert.pem)
gem install -P HighSecurity oui-offline
```

**Comment by steakknife** [comment]
@coolacid If there's an issue or feedback, feel free to open an issue.  Good luck on your project.
