### ISSUE TITLE
[REQ] Multi-platform

### ISSUE THREAD

**Issue by coolacid** [steakknife/oui#5]
Yep - this is gonna suck, but figured I'd at least document it here.

Currently, the code is platform dependent on the sqlite3 extension. Something my team and/or I might try and PR is the ability to define gems and sequel extensions based on platform (Ruby vs JRuby)

Should be able to define which gems to include at install time using this: http://en.wikibooks.org/wiki/Ruby_Programming/RubyGems#How_to_install_different_versions_of_gems_depending_on_which_version_of_ruby_the_installee_is_using

And, sequel would use the JDBC driver instead of native.

**Comment by steakknife** [comment]
Closed by #6   See also #8
